### ISSUE TITLE
Executors keep running after removing the framework

### ISSUE THREAD

**Issue by abhishekamralkar** [mesos/logstash#38] opened 2015-09-21 10:37 UTC
I installed mesos/logstash in my DCOS cluster as marathon app with options like below

"JAVA_OPTS": "-Xmx256m -Dmesos.logstash.web.port=9092 -Dmesos.logstash.framework.name=marathon-logstashv1 -Dmesos.logstash.logstash.heap.size=256 -Dmesos.logstash.executor.heap.size=512 -Dmesos.zk=zk://master.mesos:2181 -Dmesos.logstash.volumes=/var/log/mesos"

but it never worked , we found issues like docker containers log files never get observed.

When we killed the app , logstash executor kept running and also we removed the logstash framework from zokeeper , logstash tasks kept running .

**Comment by frankscholten** [comment] 2015-09-22 12:14
Thanks for reporting this issue @abhishekamralkar

**Comment by jhftrifork** [comment] 2016-01-28 10:03
@abhishekamralkar are you still experiencing this issue? The framework has changed substantially since this issue and I'm unsure whether we can reproduce it. Are there any more details we require?

**Comment by abhishekamralkar** [comment] 2016-01-28 18:46
@jhftrifork unfortunately I am not using mesos/logstash anymore , as currently its not able to send logs to Kafka topic , so I chhoosen to run vanilla logstash as marathon tasks and have them send logs to Kafka topic.

**Comment by jhftrifork** [comment] 2016-01-29 10:25
@abhishekamralkar okay, thanks. I'll close this one unless we get further reports of the same thing.

**Closed by jhftrifork** 2016-01-29 10:25 UTC
Labels: bug
