### ISSUE TITLE
Failed to detect a master: Failed to parse data of unknown label 'json.info'

### ISSUE THREAD

**Issue by canadatom** [mesos/logstash#62] opened 2015-12-15 16:37 UTC
Here is my logstash json for marathon

```json
{
   "id": "/logstash",
   "cpus": 2,
   "mem": 1024.0,
   "instances": 1,
   "container": {
     "type": "DOCKER",
     "docker": {
       "image": "mesos/logstash-scheduler:0.0.6",
       "network": "HOST"
     }
   },
   "env": {
     "JAVA_OPTS": "-Dmesos.logstash.framework.name=logstash_framework -Dmesos.zk=zk://node-1:2181,node-2:2181,node-3:2181/mesos"
   }
 }
```

```
I1215 16:28:02.958233 17601 exec.cpp:133] Version: 0.24.1
I1215 16:28:02.961136 17609 exec.cpp:207] Executor registered on slave 20151215-143223-1750233610-5050-1-S2
Warning: '-c' is deprecated, it will be replaced by '--cpu-shares' soon. See usage.
2015-12-15 16:28:08,078:6(0x7fd5d76de700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
2015-12-15 16:28:08,078:6(0x7fd5d76de700):ZOO_INFO@log_env@716: Client environment:host.name=OCLD1LX-MESOS-S3
2015-12-15 16:28:08,078:6(0x7fd5d76de700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
2015-12-15 16:28:08,078:6(0x7fd5d76de700):ZOO_INFO@log_env@724: Client environment:os.arch=3.10.0-327.3.1.el7.x86_64
2015-12-15 16:28:08,078:6(0x7fd5d76de700):ZOO_INFO@log_env@725: Client environment:os.version=#1 SMP Wed Dec 9 14:09:15 UTC 2015
2015-12-15 16:28:08,078:6(0x7fd5d76de700):ZOO_INFO@log_env@733: Client environment:user.name=(null)
2015-12-15 16:28:08,078:6(0x7fd5d76de700):ZOO_INFO@log_env@741: Client environment:user.home=/root
2015-12-15 16:28:08,078:6(0x7fd5d76de700):ZOO_INFO@log_env@753: Client environment:user.dir=/
2015-12-15 16:28:08,078:6(0x7fd5d76de700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=node-1:2181,node-2:2181,node-3:2181 sessionTimeout=20000 watcher=0x7fd601bd2a60 sessionId=0 sessionPasswd=<null> context=0x7fd5cc003270 flags=0
2015-12-15 16:28:08,095:6(0x7fd5d2ed5700):ZOO_INFO@check_events@1703: initiated connection to server [10.114.82.117:2181]
2015-12-15 16:28:08,097:6(0x7fd5d2ed5700):ZOO_INFO@check_events@1750: session establishment complete on server [10.114.82.117:2181], sessionId=0x351a616af790050, negotiated timeout=20000
2015-12-15 16:28:08,314:6(0x7fd5d46d8700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
2015-12-15 16:28:08,314:6(0x7fd5d46d8700):ZOO_INFO@log_env@716: Client environment:host.name=OCLD1LX-MESOS-S3
2015-12-15 16:28:08,314:6(0x7fd5d46d8700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
2015-12-15 16:28:08,314:6(0x7fd5d46d8700):ZOO_INFO@log_env@724: Client environment:os.arch=3.10.0-327.3.1.el7.x86_64
2015-12-15 16:28:08,314:6(0x7fd5d46d8700):ZOO_INFO@log_env@725: Client environment:os.version=#1 SMP Wed Dec 9 14:09:15 UTC 2015
I1215 16:28:08.314399    21 sched.cpp:157] Version: 0.22.1
2015-12-15 16:28:08,314:6(0x7fd5d46d8700):ZOO_INFO@log_env@733: Client environment:user.name=(null)
2015-12-15 16:28:08,314:6(0x7fd5d46d8700):ZOO_INFO@log_env@741: Client environment:user.home=/root
2015-12-15 16:28:08,314:6(0x7fd5d46d8700):ZOO_INFO@log_env@753: Client environment:user.dir=/
2015-12-15 16:28:08,314:6(0x7fd5d46d8700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=node-1:2181,node-2:2181,node-3:2181 sessionTimeout=10000 watcher=0x7fd601bd2a60 sessionId=0 sessionPasswd=<null> context=0x1fe52e0 flags=0
2015-12-15 16:28:08,336:6(0x7fd5d1ed3700):ZOO_INFO@check_events@1703: initiated connection to server [10.115.255.228:2181]
2015-12-15 16:28:08,346:6(0x7fd5d1ed3700):ZOO_INFO@check_events@1750: session establishment complete on server [10.115.255.228:2181], sessionId=0x151a613b0760051, negotiated timeout=10000
I1215 16:28:08.349599    37 group.cpp:313] Group process (group(1)@10.114.49.179:56925) connected to ZooKeeper
I1215 16:28:08.349645    37 group.cpp:790] Syncing group operations: queue size (joins, cancels, datas) = (0, 0, 0)
I1215 16:28:08.349659    37 group.cpp:385] Trying to create path '/mesos' in ZooKeeper
I1215 16:28:08.395557    37 detector.cpp:138] Detected a new leader: (id='25')
I1215 16:28:08.395725    37 group.cpp:659] Trying to get '/mesos/json.info_0000000025' in ZooKeeper
Failed to detect a master: Failed to parse data of unknown label 'json.info'
```

**Comment by mcuervoe** [comment] 2015-12-29 13:42
It stops working in mesos 0.24 I think it is related to this:

https://issues.apache.org/jira/browse/MESOS-2340
https://issues.apache.org/jira/browse/MESOS-3135


the elasticsearch project also suffered the same problem:

https://github.com/mesos/elasticsearch/issues/338

**Comment by jhftrifork** [comment] 2016-01-05 11:01
Duplicate of #59. @canadatom @mcuervoe thanks for reporting! I'll look at this on the other ticket

**Closed by jhftrifork** 2016-01-05 11:01 UTC

**Comment by abhishekamralkar** [comment] 2016-01-16 01:12
@jhftrifork any updates on fix to this ?
